[features]
seeds = false
[programs.localnet]
counter = "ETADTkKg9XhkeQLkRNZc7Pjwx64AX5FenSkCxRxSMNVV"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/vishnukvs/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
